import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const sansx = localFont({
  src: [
    {
      path: "../fonts/IRANSansX-Thin.woff2",
      weight: "100",
      style: "normal",
    },
    {
      path: "../fonts/IRANSansX-UltraLight.woff2",
      weight: "200",
      style: "normal",
    },
    {
      path: "../fonts/IRANSansX-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../fonts/IRANSansX-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/IRANSansX-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../fonts/IRANSansX-Bold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../fonts/IRANSansX-ExtraBold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../fonts/IRANSansX-Black.woff2",
      weight: "800",
      style: "normal",
    },
    {
      path: "../fonts/IRANSansX-ExtraBlack.woff2",
      weight: "900",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "هموطــــن 24",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body className={sansx.className}>{children}</body>
    </html>
  );
}
